import type { Zone, ContentModule } from './types';

export const ZONES: Zone[] = [
  {
    id: 'fashion',
    name: 'Fashion Avenue',
    tagline: 'The World\'s Most Coveted Address in Retail',
    area: '2.4M sq ft',
    stats: [
      { label: 'Luxury Brands', value: '200+' },
      { label: 'Daily Visitors', value: '180K' },
      { label: 'Avg Spend/Visit', value: 'AED 1,200' },
    ],
    description: 'An unrivalled concentration of global luxury and aspirational brands within a single dedicated luxury precinct.',
    color: 'from-amber-950 to-stone-950',
    accentColor: '#D4AF37',
    image: 'https://images.pexels.com/photos/1536619/pexels-photo-1536619.jpeg?w=1400',
    gridArea: 'fashion',
  },
  {
    id: 'luxury',
    name: 'Luxury Spine',
    tagline: 'Where Heritage and Ambition Converge',
    area: '1.1M sq ft',
    stats: [
      { label: 'Ultra-HNW Clients', value: '42K/mo' },
      { label: 'Flagship Boutiques', value: '85' },
      { label: 'Brand Prestige Score', value: '98/100' },
    ],
    description: 'The single most high-density concentration of ultra-premium brands in the Middle East, serving the region\'s most affluent clientele.',
    color: 'from-zinc-900 to-neutral-950',
    accentColor: '#C0A060',
    image: 'https://images.pexels.com/photos/1488463/pexels-photo-1488463.jpeg?w=1400',
    gridArea: 'luxury',
  },
  {
    id: 'entertainment',
    name: 'Entertainment District',
    tagline: 'Entertainment at a Scale That Redefines the Category',
    area: '3.8M sq ft',
    stats: [
      { label: 'Annual Visitors', value: '105M' },
      { label: 'Attractions', value: '160+' },
      { label: 'Dwell Time', value: '4.2 hrs' },
    ],
    description: 'The most visited entertainment destination on the planet—from Dubai Aquarium to VR parks, Olympic-size ice rinks to rooftop cinemas.',
    color: 'from-slate-900 to-blue-950',
    accentColor: '#3B82F6',
    image: 'https://images.pexels.com/photos/2506923/pexels-photo-2506923.jpeg?w=1400',
    gridArea: 'entertainment',
  },
  {
    id: 'dining',
    name: 'Dining Boulevard',
    tagline: 'A Culinary World of Its Own',
    area: '900K sq ft',
    stats: [
      { label: 'Restaurants', value: '200+' },
      { label: 'Michelin Concepts', value: '14' },
      { label: 'Daily Covers', value: '85K' },
    ],
    description: 'From three-Michelin-star conceptual dining to authentic street food from 60 cuisines—an unmatched culinary destination.',
    color: 'from-red-950 to-stone-950',
    accentColor: '#EF4444',
    image: 'https://images.pexels.com/photos/941861/pexels-photo-941861.jpeg?w=1400',
    gridArea: 'dining',
  },
  {
    id: 'events',
    name: 'Events Plaza',
    tagline: 'Where Global Moments Are Made',
    area: '1.6M sq ft',
    stats: [
      { label: 'Events/Year', value: '500+' },
      { label: 'Max Capacity', value: '120K' },
      { label: 'Live Reach', value: '2.1B' },
    ],
    description: 'The world\'s largest events and activation canvas—from international music acts and fashion shows to brand launches and sporting spectacles.',
    color: 'from-violet-950 to-slate-950',
    accentColor: '#8B5CF6',
    image: 'https://images.pexels.com/photos/1190297/pexels-photo-1190297.jpeg?w=1400',
    gridArea: 'events',
  },
];

export const CONTENT_MODULES: ContentModule[] = [
  {
    id: 'retail',
    title: 'Retail Performance',
    headline: '105 Million Visitors. One Address. Yours.',
    subtext: 'Dubai Mall is not a shopping centre in the conventional sense — it is a global destination that commands the sustained attention and expenditure of the world\'s most discerning consumers.',
    stats: [
      { value: '105M', label: 'Annual Footfall', prefix: '' },
      { value: '82%', label: 'International Visitors', prefix: '' },
      { value: '14%', label: 'Year-on-Year Sales Growth', prefix: '+' },
      { value: 'AED 28B', label: 'Annual Retail Sales', prefix: '' },
    ],
    image: 'https://images.pexels.com/photos/1005638/pexels-photo-1005638.jpeg?w=1400',
    relevantFor: ['retail', 'sponsor'],
  },
  {
    id: 'luxury',
    title: 'Luxury Positioning',
    headline: 'The Clientele That Defines the Luxury Conversation',
    subtext: 'Our visitor profile is without parallel — a consistently affluent, internationally connected audience spending at the highest price points, across every category, throughout every season.',
    stats: [
      { value: '42K', label: 'Ultra-HNW Visitors Per Month', prefix: '' },
      { value: 'AED 4,800', label: 'Average Luxury Spend Per Visit', prefix: '' },
      { value: '68%', label: 'Returning Premium Visitors', prefix: '' },
      { value: '#1', label: 'Luxury Retail Destination, GCC', prefix: '' },
    ],
    image: 'https://images.pexels.com/photos/1488463/pexels-photo-1488463.jpeg?w=1400',
    relevantFor: ['retail', 'sponsor'],
  },
  {
    id: 'dining',
    title: 'Dining & Lifestyle',
    headline: 'Stay Longer. Spend More. Return with Pleasure.',
    subtext: 'Our dining and lifestyle ecosystem is thoughtfully designed to extend the time visitors spend here — and in doing so, deepens their connection with every brand they encounter.',
    stats: [
      { value: '4.2hrs', label: 'Average Dwell Time', prefix: '' },
      { value: '200+', label: 'Dining Concepts', prefix: '' },
      { value: '85K', label: 'Daily Restaurant Covers', prefix: '' },
      { value: '3.8x', label: 'Spend Uplift vs. Standalone Retail', prefix: '' },
    ],
    image: 'https://images.pexels.com/photos/941861/pexels-photo-941861.jpeg?w=1400',
    relevantFor: ['retail', 'event'],
  },
  {
    id: 'entertainment',
    title: 'Entertainment',
    headline: 'We Don\'t Compete with Entertainment Venues. We Contain Them.',
    subtext: 'From the world\'s largest aquarium to indoor ski slopes and live performance arenas — Dubai Mall\'s entertainment offering is not a feature. It is a destination in its own right.',
    stats: [
      { value: '160+', label: 'Distinct Attractions', prefix: '' },
      { value: '12M', label: 'Entertainment Visitors Per Year', prefix: '' },
      { value: '98%', label: 'Visitor Satisfaction Rating', prefix: '' },
      { value: 'AED 2.1B', label: 'Entertainment Revenue', prefix: '' },
    ],
    image: 'https://images.pexels.com/photos/2506923/pexels-photo-2506923.jpeg?w=1400',
    relevantFor: ['sponsor', 'event'],
  },
  {
    id: 'events',
    title: 'Events Platform',
    headline: 'Your Brand. The World\'s Most Watched Stage.',
    subtext: 'No events platform on Earth combines this concentration of global media, ultra-high-net-worth attendees, and real-time digital amplification — all within a single, iconic address.',
    stats: [
      { value: '500+', label: 'Events Staged Annually', prefix: '' },
      { value: '2.1B', label: 'Global Media Impressions', prefix: '' },
      { value: '120K', label: 'Single-Event Capacity', prefix: '' },
      { value: '180+', label: 'Countries Reached', prefix: '' },
    ],
    image: 'https://images.pexels.com/photos/1190297/pexels-photo-1190297.jpeg?w=1400',
    relevantFor: ['event', 'sponsor'],
  },
];

export const STORY_BENEFITS: Record<string, {
  id: string;
  chapter: string;
  headline: string;
  body: string;
  pull: string;
  image: string;
  accentColor: string;
  metric: { value: string; label: string };
}[]> = {
  retail: [
    {
      id: 'r1',
      chapter: 'The Footfall',
      headline: 'Your brand, encountered by 105 million people a year.',
      body: 'Consider what it means to open a flagship at the world\'s most visited address. Dubai Mall is not simply a shopping destination — it is a daily ritual for millions. Visitors don\'t pass through; they linger. Your store becomes part of that experience.',
      pull: '"The world doesn\'t come to Dubai. It comes to Dubai Mall."',
      image: 'https://images.pexels.com/photos/1005638/pexels-photo-1005638.jpeg?auto=compress&cs=tinysrgb&w=1600',
      accentColor: '#D4AF37',
      metric: { value: '105M', label: 'Annual visitors' },
    },
    {
      id: 'r2',
      chapter: 'The Clientele',
      headline: 'The customer you\'ve been seeking is already here.',
      body: '82% of our visitors arrive from abroad — a self-selected cohort of globally mobile, high-spending individuals. They did not come to browse idly; they came with intent to purchase. The average luxury spend per visit is AED 4,800. This is not a demographic profile. This is your ideal customer, in the building.',
      pull: '42,000 ultra-high-net-worth visitors pass through every month.',
      image: 'https://images.pexels.com/photos/1488463/pexels-photo-1488463.jpeg?auto=compress&cs=tinysrgb&w=1600',
      accentColor: '#C0A060',
      metric: { value: '82%', label: 'International visitors' },
    },
    {
      id: 'r3',
      chapter: 'The Dwell Time',
      headline: 'They don\'t just visit. They stay for over four hours.',
      body: 'With more than 200 dining destinations, world-class entertainment and a curated lifestyle ecosystem, the average visitor spends 4.2 hours here per trip. That is 4.2 hours of discovery, consideration, and purchase intent — all unfolding beneath the same roof as your brand.',
      pull: 'Shoppers at Dubai Mall spend 3.8× more than at a standalone retail location.',
      image: 'https://images.pexels.com/photos/941861/pexels-photo-941861.jpeg?auto=compress&cs=tinysrgb&w=1600',
      accentColor: '#D4AF37',
      metric: { value: '4.2 hrs', label: 'Average dwell time per visit' },
    },
  ],
  sponsor: [
    {
      id: 's1',
      chapter: 'The Reach',
      headline: 'Not an advertisement. A global cultural moment.',
      body: 'Sponsoring at Dubai Mall is not a media buy in the conventional sense. It is entry into a living media ecosystem that generates 2.1 billion impressions annually. Whatever unfolds here is photographed, shared, and amplified across 180 countries within hours.',
      pull: '"The most photographed commercial interior on Earth."',
      image: 'https://images.pexels.com/photos/2506923/pexels-photo-2506923.jpeg?auto=compress&cs=tinysrgb&w=1600',
      accentColor: '#3B82F6',
      metric: { value: '2.1B', label: 'Annual global impressions' },
    },
    {
      id: 's2',
      chapter: 'The Exclusivity',
      headline: 'Your category. Your name. No competition.',
      body: 'We partner with one brand per category. When visitors encounter your presence here, there is no rival in the frame — no diluted message, no divided attention. Just your brand, commanding the full regard of 105 million people.',
      pull: 'Exclusive access to 105 million consumers — yours alone.',
      image: 'https://images.pexels.com/photos/1190297/pexels-photo-1190297.jpeg?auto=compress&cs=tinysrgb&w=1600',
      accentColor: '#60A5FA',
      metric: { value: '#1', label: 'Brand visibility index, GCC' },
    },
    {
      id: 's3',
      chapter: 'The Setting',
      headline: 'A venue this iconic does half the storytelling for you.',
      body: 'From the Dubai Fountain to the Grand Atrium, every element of Dubai Mall was conceived for spectacle. When your brand is present here, the environment elevates it. Visitors do not observe an activation — they are immersed within one.',
      pull: 'Up to 120,000 guests can attend a single live activation.',
      image: 'https://images.pexels.com/photos/1005638/pexels-photo-1005638.jpeg?auto=compress&cs=tinysrgb&w=1600',
      accentColor: '#3B82F6',
      metric: { value: '120K', label: 'Peak live event capacity' },
    },
  ],
  explore: [
    {
      id: 'x1',
      chapter: 'The Scale',
      headline: '105 million visitors. One extraordinary address.',
      body: 'Dubai Mall is not merely a shopping destination. It is a city within a city — a self-contained world of retail, dining, entertainment and culture that draws more visitors each year than any other built destination on Earth.',
      pull: '"A footfall that rivals the tourism figures of entire nations."',
      image: 'https://images.pexels.com/photos/1005638/pexels-photo-1005638.jpeg?auto=compress&cs=tinysrgb&w=1600',
      accentColor: '#A3A3A3',
      metric: { value: '105M', label: 'Annual visitors' },
    },
    {
      id: 'x2',
      chapter: 'The Audience',
      headline: 'The world\'s most sought-after consumer, under one roof.',
      body: '82% of our visitors are international. 42,000 ultra-high-net-worth guests arrive each month. The average dwell time is 4.2 hours. Whatever your ambition — retail, events, sponsorship or hospitality — the audience you require is already present.',
      pull: 'A globally mobile, discerning audience — present every day, all year.',
      image: 'https://images.pexels.com/photos/2506923/pexels-photo-2506923.jpeg?auto=compress&cs=tinysrgb&w=1600',
      accentColor: '#A3A3A3',
      metric: { value: '82%', label: 'International visitors' },
    },
    {
      id: 'x3',
      chapter: 'The Platform',
      headline: 'Every format. Every scale. One remarkable venue.',
      body: 'Flagship retail. Landmark events. Category-exclusive sponsorships. Pop-up activations. Celebrated dining partnerships. Dubai Mall is not one opportunity — it is a portfolio of them. Explore every dimension and discover where you belong.',
      pull: '500+ events each year. 2.1 billion global impressions.',
      image: 'https://images.pexels.com/photos/1190297/pexels-photo-1190297.jpeg?auto=compress&cs=tinysrgb&w=1600',
      accentColor: '#A3A3A3',
      metric: { value: '500+', label: 'Events per year' },
    },
  ],
  event: [
    {
      id: 'e1',
      chapter: 'The Audience',
      headline: 'Your audience is already here. You simply need to arrive.',
      body: 'Most venues require you to build an audience from scratch. Here, 105 million people pass through each year. Whether you are planning a product launch, a cultural programme or an intimate showcase, the most significant challenge has already been resolved.',
      pull: '"Every day at Dubai Mall feels like opening night."',
      image: 'https://images.pexels.com/photos/1190297/pexels-photo-1190297.jpeg?auto=compress&cs=tinysrgb&w=1600',
      accentColor: '#EF4444',
      metric: { value: '500+', label: 'Events staged annually' },
    },
    {
      id: 'e2',
      chapter: 'The Flexibility',
      headline: 'An intimate dinner or 120,000 guests — the same address.',
      body: 'We have hosted private dinners for 80 and product launches for 120,000. Month-long cultural festivals spanning five distinct zones. A single evening that felt like a city awakening. Whatever scale you require, this venue has accommodated more — and stands ready for yours.',
      pull: 'Any scale. One address. No compromise.',
      image: 'https://images.pexels.com/photos/941861/pexels-photo-941861.jpeg?auto=compress&cs=tinysrgb&w=1600',
      accentColor: '#F87171',
      metric: { value: '120K', label: 'Peak single-event capacity' },
    },
    {
      id: 'e3',
      chapter: 'The Amplification',
      headline: 'What happens here is witnessed across 180 countries.',
      body: 'Events at Dubai Mall do not remain within Dubai. Our media infrastructure and the extraordinary volume of content produced here ensures your event reaches a global audience in real time. 2.1 billion impressions. 180 countries. Often within a single evening.',
      pull: 'No venue on Earth transforms a single night into a global occasion quite like this.',
      image: 'https://images.pexels.com/photos/2506923/pexels-photo-2506923.jpeg?auto=compress&cs=tinysrgb&w=1600',
      accentColor: '#EF4444',
      metric: { value: '2.1B', label: 'Annual global impressions' },
    },
  ],
};

export const PATH_CONFIG = {
  retail: {
    label: 'Retail Partner',
    headline: 'Secure Your Address at the World\'s Most Visited Mall',
    subheadline: 'Everything you need to understand what a presence at Dubai Mall means for your brand.',
    modules: ['retail', 'luxury', 'dining'],
    color: '#D4AF37',
  },
  sponsor: {
    label: 'Brand & Sponsor',
    headline: 'Place Your Brand at the Centre of Global Attention.',
    subheadline: 'Discover the full range of sponsorship, activation and media opportunities available here.',
    modules: ['retail', 'entertainment', 'events'],
    color: '#3B82F6',
  },
  event: {
    label: 'Event Partner',
    headline: 'Your Vision. The World\'s Most Celebrated Venue.',
    subheadline: 'Explore what becomes possible when you choose Dubai Mall as your stage.',
    modules: ['events', 'entertainment', 'dining'],
    color: '#EF4444',
  },
  explore: {
    label: 'Exploring',
    headline: 'Discover Everything Dubai Mall Has to Offer',
    subheadline: 'Retail, events, sponsorship and beyond — a complete picture of what awaits.',
    modules: ['retail', 'luxury', 'dining', 'entertainment', 'events'],
    color: '#A3A3A3',
  },
};
